---
title: "PhyloTree Script"
author: "Vivek Ramanan"
date: "3/15/2021"
output: html_document
---

```{r cars}
library(ggtree)
library(ggplot2)
library(treeio)
library(ggnewscale)
library(ape)
library(dendextend)
library(dplyr)
d <- read.csv("/users/vivekramanan/Desktop/Research/hostUpdate-Current.csv")
```

## ORAL

```{r}
O_tree <- treeio::read.nexus("../paupFiles/run6-chosenPhyla/oral_choPhyla.tre")
```

```{r}
ggtree(O_tree) %<+% d + 
  geom_tippoint(aes(shape=Diet, color=Diet), size=4)
#ggsave("../trees/run6-chosenPhyla/oral_branchLengths.png")
```


```{r fig1, fig.height=10, fig.width=10}
oral_clades <- c(60)
p <- ggtree(O_tree, branch.length = "none") %<+% d
p2 <- p + geom_tiplab(offset=0.5) + geom_tippoint(aes(shape=Diet, color=Diet), size=3) +
         geom_hilight(mapping=aes(subset= node %in% oral_clades,node = node)) +
          labs(fill = "domesticated clade" )

df <- d[d$Newick_label %in% O_tree$tip.label,]
df <- df[match(O_tree$tip.label, df$Newick_label),]
classLabels <- df[6]
Domestication <- df[8]
rownames(classLabels) <- O_tree$tip.label
rownames(Domestication) <- O_tree$tip.label

p3 <- gheatmap(p2, classLabels, offset=7, width=0.1) + 
  scale_fill_viridis_d(option="D", name="Taxonomical\nClass", direction=-1, begin=0.25)
p4 <- p3 + new_scale_fill()
p5 <- gheatmap(p4, Domestication, offset=10, width=0.1) + 
  scale_fill_manual(breaks=c("D", "W"), values=c("orange", "navyblue"), name="Domestication")
p5

#ggsave("../trees/run6-chosenPhyla/oral_rectangular.png")
```
```{r, fig.height=3, fig.width=5}
oral_clades <- c(60)
p <- ggtree(O_tree) %<+% d
p2 <- p + geom_tiplab(as_ylab=TRUE,offset=0.5) + geom_tippoint(aes(shape=Diet, color=Diet), size=3) +
         geom_hilight(mapping=aes(subset= node %in% oral_clades,node = node)) +
          labs(fill = "domesticated clade" )

df <- d[d$Newick_label %in% O_tree$tip.label,]
df <- df[match(O_tree$tip.label, df$Newick_label),]
classLabels <- df[6]
Domestication <- df[8]
rownames(classLabels) <- O_tree$tip.label
rownames(Domestication) <- O_tree$tip.label

p3 <- gheatmap(p2, classLabels, offset=0.05, width=0.1) + 
  scale_fill_viridis_d(option="D", name="Taxonomical\nClass", direction=-1, begin=0.25)
p4 <- p3 + new_scale_fill()
p5 <- gheatmap(p4, Domestication, offset=0.1, width=0.1) + 
  scale_fill_manual(breaks=c("D", "W"), values=c("orange", "navyblue"), name="Domestication")
p5

#ggsave("../trees/run6-chosenPhyla/oral_test.png")
```


## GI
```{r}
#tree <- read.tree()
tree <- treeio::read.nexus("../paupFiles/run6-chosenPhyla/gi_choPhyla.tre")
```

```{r fig1, fig.height=10, fig.width=10}
ggtree(tree) %<+% d + 
  geom_tippoint(aes(shape=Diet, color=Diet), size=4)
ggsave("../trees/run6-chosenPhyla/gi_branchLengths.png")
```
```{r fig2, fig.height=15, fig.width=10}
ggtree(tree) + geom_text(aes(label=node)) + geom_tiplab()
```


```{r fig2, fig.height=15, fig.width=10}
#gi_clades <- c(257, 274, 276, 208, 201)
gi_clades <- c(252, 214, 182, 266, 273)
p <- ggtree(tree, branch.length = "none")  %<+% d 
p2 <- p + geom_tiplab(offset=0.5) + geom_tippoint(aes(shape=Diet, color=Diet), size=3) +
          geom_hilight(mapping=aes(subset= node %in% gi_clades,node = node, fill=as.factor(node))) +
          labs(fill = "GI clade" )

df <- d[d$Newick_label %in% tree$tip.label,]
df <- df[match(tree$tip.label, df$Newick_label),]
classLabels <- df[6]
Domestication <- df[8]
rownames(classLabels) <- tree$tip.label
rownames(Domestication) <- tree$tip.label

p2 <- p2 + new_scale_fill()
p3 <- gheatmap(p2, classLabels, offset=7, width=0.1) + 
  scale_fill_viridis_d(option="D", name="Taxonomical\nClass", direction=-1, begin=0.25)
p4 <- p3 + new_scale_fill()
p5 <- gheatmap(p4, Domestication, offset=10, width=0.1) + 
  scale_fill_manual(breaks=c("D", "W"), values=c("orange", "navyblue"), name="Domestication")
p5
ggsave("../trees/run6-chosenPhyla/gi_rectangular.png")
```
```{r fig3, fig.height=10, fig.width=10}
#gi_clades <- c(257, 274, 276, 208, 201)
gi_clades <- c(252, 214, 182, 266, 273)
p <- ggtree(tree, branch.length = "none", layout="circular")  %<+% d 
p2 <- p + geom_tiplab(offset=0.5) + geom_tippoint(aes(shape=Diet, color=Diet), size=3) +
          geom_hilight(mapping=aes(subset= node %in% gi_clades,node = node, fill=as.factor(node))) +
          labs(fill = "GI clade" )
df <- d[d$Newick_label %in% tree$tip.label,]
df <- df[match(tree$tip.label, df$Newick_label),]
classLabels <- df[6]
Domestication <- df[8]
rownames(classLabels) <- tree$tip.label
rownames(Domestication) <- tree$tip.label

p2 <- p2 + new_scale_fill()
p3 <- gheatmap(p2, classLabels, offset=12, width=0.1, colnames_angle=30, colnames_offset_y = .05) + 
  scale_fill_viridis_d(option="D", name="Taxonomical\nClass", direction=-1, begin=0.25)
p4 <- p3 + new_scale_fill()
p5 <- gheatmap(p4, Domestication, offset=15, width=0.1, colnames_angle=30, colnames_offset_y = 0.0) + 
  scale_fill_manual(breaks=c("D", "W"), values=c("orange", "navyblue"), name="Domestication")
p5
ggsave("../trees/run6-chosenPhyla/gi_circular.png")
```
```{r}
x <- treeio::read.nexus("../paupFiles/run6-chosenPhyla/gi_choTangle.tre")
y <- treeio::read.nexus("../paupFiles/run6-chosenPhyla/oral_choTangle.tre")
```
```{r}
p <- ggtree(x) + geom_text(aes(label=node)) + geom_tiplab()
#p <- flip(p, 41, 31)
p
```

```{r}
oral_nodes = c(31)
#gi_nodes = c(40)
gi_nodes = c(41, 45, 36)
p1 <- ggtree(x) +
        geom_hilight(mapping=aes(subset= node %in% gi_nodes,node = node)) 

p2 <- ggtree(y)  %<+% d
p2 <- flip(p2, 41, 31)
# run3: 42 and 31 
# run4: 21 and 31
# run5: 29 and 39

d1 <- p1$data
d2 <- p2$data

d2$x <- max(d2$x) - d2$x + max(d1$x) + 1
```
```{r fig5}
pp <- p1 %<+% d+ geom_tree(data=d2)+   
  geom_hilight(data=d2, mapping=aes(subset= node %in% oral_nodes, node=node)) + 
  labs(fill = "clades for tree in right" )

dd <- dplyr::bind_rows(d1, d2) %>% filter(!is.na(label))

df <- d[d$Newick_label %in% dd$label,]
df <- df[match(dd$label, df$Newick_label),]
dd$domestication <- df$domestication
 
tangle <- pp + ggnewscale::new_scale_fill() +
        geom_line(aes(x,y,group=label), data=dd, alpha=0.5)
tangle <- tangle + new_scale_fill() +
        geom_tippoint(aes(shape=Diet, color=Diet), size=3) + 
        geom_tippoint(data=d2, aes(shape=Diet, color=Diet), size=3)
        #scale_color_viridis_d(option="D",direction=-1, begin=0.25) 
tangle
ggsave("../trees/run6-chosenPhyla/tanglegram.png")
```

